[workspace]
members = [
    "rts_core",
    "rts_server",
    "rts_client_wasm",
    # Add other crates like rts_admin_ui if needed later
]

resolver = "2" # Use the latest resolver

# Optional: Define shared profiles for all members
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[profile.dev]
opt-level = 1 # Faster builds during development
